package Vista;

import Controlador.UsuarioCtrl;
import Modelo.Hash;
import Modelo.UsuarioDataLogin;
import javax.swing.JOptionPane;

public class RegistroUsuario extends javax.swing.JFrame {

    //instancia al controlador
    UsuarioCtrl usrcrtl = new UsuarioCtrl();
    UsuarioDataLogin usrlog = new UsuarioDataLogin();
    RegistroUsuario frmRegistroUser;
    Home frmHome;

    public RegistroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        //LlenarUsrCombox();
    }

    RegistroUsuario(UsuarioDataLogin usrlog) {
        this.usrlog=usrlog;
        //JOptionPane.showMessageDialog(null, "Intenta guardar un registro: " + usrlog.getId_rol()); //To change body of generated methods, choose Tools | Templates.
        if (usrlog.getId_rol() == 1) {
            initComponents();
            setLocationRelativeTo(null);
            LlenarUsrCombox();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        cboTipoRol = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabelCarnet = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtConfirmContrasenia = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Nuevo Usuario");

        jLabelTipoUsuario.setText("Tipo Usuario:");

        cboTipoRol.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelNombre.setText("Nombre:");

        jLabelApellido.setText("Apellido:");

        jLabelCarnet.setText("Carnet:");

        jLabelContraseña.setText("Contraseña:");

        jLabel2.setText("<html>Confirmar Contraseña:</html>");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancenlar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelContraseña)
                    .addComponent(jLabelCarnet)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnRegistrar))
                    .addComponent(cboTipoRol, 0, 189, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido)
                    .addComponent(txtCarnet)
                    .addComponent(jLabel1)
                    .addComponent(txtContrasenia)
                    .addComponent(txtConfirmContrasenia))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(cboTipoRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCarnet)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseña)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //lenar combobox

    private void LlenarUsrCombox() {
        cboTipoRol.addItem("Administrador");
        cboTipoRol.addItem("Profesor");
        cboTipoRol.addItem("Alumno");
    }

    //accion al dar click en registrar
    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        String opcion = (String) cboTipoRol.getSelectedItem();
        //Llamada al metodo guardar
        if (opcion.equals("Administrador")) {
            guardarAdmin();
            System.out.println("Selecciono un: " + opcion);
        }
        if (opcion.equals("Profesor")) {
            guardarProfesor();
            System.out.println("Selecciono un: " + opcion);

        }
        if (opcion.equals("Alumno")) {
            guardarAlumno();
            System.out.println("Selecciono un: " + opcion);

        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        //muestra home
        mostrarHome();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void guardarAdmin() {
        String contra = new String(txtContrasenia.getPassword());
        String contraConfirm = new String(txtConfirmContrasenia.getPassword());
        //validar campos vacios
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCarnet.getText().equals("") || txtContrasenia.equals("") || txtConfirmContrasenia.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.");
        } else {
            //comparamos la contrasenia
            if (contra.equals(contraConfirm)) {
                //ciframos la contraseña
                String nuevaContra = Hash.sha1(contra);
                //enviamos los datos
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String carnet = txtCarnet.getText();
                String contrasenia = nuevaContra;
                int id_rol = 1;
                usrcrtl.Guardar(nombre, apellido, carnet, contrasenia, id_rol);
                limpiarInputs();
                mostrarHome();
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            }
        }
    }

    private void guardarProfesor() {
        String contra = new String(txtContrasenia.getPassword());
        String contraConfirm = new String(txtConfirmContrasenia.getPassword());
        //validar campos vacios
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCarnet.getText().equals("") || txtContrasenia.equals("") || txtConfirmContrasenia.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.");
        } else {
            //comparamos la contrasenia
            if (contra.equals(contraConfirm)) {
                //ciframos la contraseña
                String nuevaContra = Hash.sha1(contra);
                //enviamos los datos
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String carnet = txtCarnet.getText();
                String contrasenia = nuevaContra;
                int id_rol = 2;
                usrcrtl.Guardar(nombre, apellido, carnet, contrasenia, id_rol);
                limpiarInputs();
                mostrarHome();
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            }
        }
    }

    private void guardarAlumno() {
        String contra = new String(txtContrasenia.getPassword());
        String contraConfirm = new String(txtConfirmContrasenia.getPassword());
        //validar campos vacios
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCarnet.getText().equals("") || txtContrasenia.equals("") || txtConfirmContrasenia.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.");
        } else {
            //comparamos la contrasenia
            if (contra.equals(contraConfirm)) {
                //ciframos la contraseña
                String nuevaContra = Hash.sha1(contra);
                //enviamos los datos
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String carnet = txtCarnet.getText();
                String contrasenia = nuevaContra;
                int id_rol = 3;
                usrcrtl.Guardar(nombre, apellido, carnet, contrasenia, id_rol);
                limpiarInputs();
                mostrarHome();
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            }
        }
    }

    private void limpiarInputs() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCarnet.setText("");
        txtContrasenia.setText("");
        txtConfirmContrasenia.setText("");
    }
    
    private void mostrarHome(){
        if (frmHome == null) {
            frmHome = new Home(usrlog);
            frmHome.setVisible(true);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipoRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCarnet;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JPasswordField txtConfirmContrasenia;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
